// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSoTGm8g1yxUrdM5oZtItyM4zqQ3l2tTY',
    appId: '1:44712464821:web:d22e300d932b42862449fc',
    messagingSenderId: '44712464821',
    projectId: 'edugame-ddb9f',
    authDomain: 'edugame-ddb9f.firebaseapp.com',
    storageBucket: 'edugame-ddb9f.appspot.com',
    measurementId: 'G-0G3FM7DVZM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8unEcq2SEYGn8Vj9T0ajtKEg8qOiwQWU',
    appId: '1:44712464821:android:c83294292b9d604c2449fc',
    messagingSenderId: '44712464821',
    projectId: 'edugame-ddb9f',
    storageBucket: 'edugame-ddb9f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEexRXUbBNDMkJxlmimFqambweoTLuOxo',
    appId: '1:44712464821:ios:d558317e02f83b122449fc',
    messagingSenderId: '44712464821',
    projectId: 'edugame-ddb9f',
    storageBucket: 'edugame-ddb9f.appspot.com',
    iosBundleId: 'com.example.basic',
  );
}
